### ISSUE TITLE
Import Error: No module named 'utils'

### ISSUE THREAD

**Issue by evilplanet** [Suyash458/WiktionaryParser#18]
I'm using Python 3.5.3 on macOS in a conda environment.

As below, I cannot import this package in Terminal.

```
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 12:15:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from wiktionaryparser import WiktionaryParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/miniconda3/envs/proj_env/lib/python3.5/site-packages/wiktionaryparser/__init__.py", line 2, in <module>
    from .WikiParse import WiktionaryParser
  File "/Users/username/miniconda3/envs/proj_env/lib/python3.5/site-packages/wiktionaryparser/WikiParse.py", line 7, in <module>
    from utils import WordData, Definition, RelatedWord
ImportError: No module named 'utils'
```

**Comment by nanflasted** [comment]
Same with py363 on Linux (Ubuntu Artful)

changing 
```
from utils import ...
```
to
```
from .utils import ...
```
in the offending line seems to have fixed it.

**Comment by ookimi** [comment]
same error here, py363 on Ubuntu 16.04. 
The "from .utils import ..." fix helped, thanks @nanflasted !

**Comment by Code4SAFrankie** [comment]
Same error on Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32

>>> from wiktionaryparser import WiktionaryParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\wiktionaryparser\__init__.py", line 2, in <module>
    from .WikiParse import WiktionaryParser
  File "C:\ProgramData\Anaconda3\lib\site-packages\wiktionaryparser\WikiParse.py", line 7, in <module>
    from utils import WordData, Definition, RelatedWord
ModuleNotFoundError: No module named 'utils'

**Comment by Suyash458** [comment]
Please refer [this](https://github.com/Suyash458/WiktionaryParser/issues/17) issue. I'm not actively maintaining this project right now, will start soon. Feel free to contribute!
