### ISSUE TITLE
ImportError: cannot import name zip_longest

### ISSUE THREAD

**Issue by stevenspiel** [Suyash458/WiktionaryParser#36]
I'm getting an error when running the sample:

```
Traceback (most recent call last):
  File "/Users/steven/Desktop/d.py", line 1, in <module>
    from wiktionaryparser import WiktionaryParser
  File "/Library/Python/2.7/site-packages/wiktionaryparser/__init__.py", line 2, in <module>
    from .WikiParse import WiktionaryParser
  File "/Library/Python/2.7/site-packages/wiktionaryparser/WikiParse.py", line 6, in <module>
    from itertools import zip_longest
ImportError: cannot import name zip_longest
```

Python version `2.7`

**Comment by Suyash458** [comment]
This project works with python 3, I haven't fixed python 2 support yet.
