### ISSUE TITLE
Exception when parsing related words for "nutritiously" in English

### ISSUE THREAD

**Issue by gnatboard** [Suyash458/WiktionaryParser#47]
The parser encounters an `AttributeError` when fetching the entry for `'nutritiously'`.
```
>>> from wiktionaryparser import WiktionaryParser
>>> p = WiktionaryParser()
>>> p.fetch('nutritiously')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/wiktionaryparser.py", line 260, in fetch
    return self.get_word_data(language.lower())
  File "/usr/local/lib/python3.6/dist-packages/wiktionaryparser.py", line 117, in get_word_data
    'related': self.parse_related_words(word_contents),
  File "/usr/local/lib/python3.6/dist-packages/wiktionaryparser.py", line 221, in parse_related_words
    while not parent_tag.find_all('li'):
AttributeError: 'NoneType' object has no attribute 'find_all'
```
I tried again with nothing in `p.RELATIONS`, and it worked.
```
>>> for i in list(p.RELATIONS):
...     p.exclude_relation(i)
... 
>>> p.RELATIONS
[]
>>>
>>> p.fetch('nutritiously')
[{'etymology': 'nutritious +\u200e -ly', 'definitions': [{'partOfSpeech': 'adverb', 'text': ['nutritiously (comparative more nutritiously, superlative most nutritiously)', 'In a way that provides nutrition.'], 'relatedWords': [], 'examples': []}], 'pronunciations': {'text': [], 'audio': []}}]
```

**Comment by Suyash458** [comment]
Thanks @Surkal!, closing this
